# Generated by Django 2.0 on 2018-09-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='img_url',
        ),
    ]
