# Generated by Django 2.0 on 2018-09-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goods_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=30)),
                ('GoodsType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType')),
            ],
        ),
        migrations.CreateModel(
            name='Theme_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_img', models.ImageField(upload_to='theme_img')),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType_detail'),
        ),
    ]
