# Generated by Django 2.0 on 2018-09-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180903_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme_img1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_img', models.ImageField(upload_to='theme_img/first_slide.jpg')),
                ('goods_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.GoodsType')),
            ],
        ),
        migrations.CreateModel(
            name='Theme_img2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_img', models.ImageField(upload_to='theme_img/second_slide.jpg')),
                ('goods_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.GoodsType')),
            ],
        ),
        migrations.CreateModel(
            name='Theme_img3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_img', models.ImageField(upload_to='theme_img/third_slide.jpg')),
                ('goods_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.GoodsType')),
            ],
        ),
        migrations.RemoveField(
            model_name='theme_img',
            name='goods_type',
        ),
        migrations.DeleteModel(
            name='Theme_img',
        ),
    ]
