# Generated by Django 2.0 on 2018-08-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180828_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='img_url1',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='img_url2',
        ),
        migrations.AlterField(
            model_name='goods',
            name='Fabric_content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='style_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
